# Before using this makefile:
# 1. Build with Microsoft Visual Studio 2013.
# 2. Make sure b2 is in the PATH.
# 3. Update the *_DIR variables below to point to your local source code directories.
# 4. Run "b2 headers toolset=msvc-12.0" in the Boost source directories specified below.

TOOLSET    = msvc-12.0
DECORATION = vc120-mt-x64-1_67

include Makefile.vsall
