# Before using this makefile:
# 1. Build with Microsoft Visual Studio 2017.
# 2. Make sure b2 is in the PATH.
# 3. Update the *_DIR variables below to point to your local source code directories.
# 4. Run "b2 headers toolset=msvc-14.1" in the Boost source directories specified below.

TOOLSET    = msvc-14.1
DECORATION = vc141-mt-x64-1_67

include Makefile.vsall
