# Before using this makefile:
# 1. Make sure b2 is in the PATH.
# 2. Update the *_DIR variables below to point to your local source code directories.
# 3. Run "b2 headers toolset=clang" in the Boost source directories specified below.

TOOLSET  := clang
COMPILER := clang++

COMPILE_COMMON := -lstdc++

include Makefile.linuxall
